### ISSUE TITLE
Error when running on mac

### ISSUE THREAD

**Issue by cukarthik** [cumc-dbmi/pmi_sprint_reporter#7]
```
Traceback (most recent call last):
  File "reporter.py", line 175, in <module>
    main()
  File "reporter.py", line 170, in main
    create_tables(schema=schema)
  File "reporter.py", line 52, in create_tables
    tables = cdm_df.groupby(['table_name'])
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 3159, in groupby
    sort=sort, group_keys=group_keys, squeeze=squeeze)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/groupby.py", line 1199, in groupby
    return klass(obj, by, **kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/groupby.py", line 388, in __init__
    level=level, sort=sort)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/groupby.py", line 2148, in _get_grouper
    in_axis, name, gpr = True, gpr, obj[gpr]
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1797, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/frame.py", line 1804, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 1084, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/internals.py", line 2851, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/index.py", line 1572, in get_loc
    return self._engine.get_loc(_values_from_object(key))
  File "pandas/index.pyx", line 134, in pandas.index.IndexEngine.get_loc (pandas/index.c:3824)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:3704)
  File "pandas/hashtable.pyx", line 686, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12280)
  File "pandas/hashtable.pyx", line 694, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12231)
KeyError: 'table_name'

```

**Comment by mark-velez** [comment]
Thanks. Fixed by 33a40e7.
